### ISSUE TITLE
automatic attendance not workinh

### ISSUE THREAD

**Issue by jenish-jain** [Spidy20/Attendace_management_system#1]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "E:\juju\JTtech\STAR\Attendace_management_system\AMS_Run.py", line 329, in Fillattendances
    recognizer = cv2.face.LBPHFaceRecognizer_create()  # cv2.createLBPHFaceRecognizer()
AttributeError: module 'cv2.cv2' has no attribute 'face'

getting this error kindly help

**Comment by Spidy20** [comment]
@jenish-jain dude you need to install opencv-contrib package than this error will be solve 
Because in normal openCV package there is no LBPH and other faces algorithms 
So you need to install opencv-contrib package for access face algorithms
That's why it's showing cv2 has no attribute face 
 Please follow me and star my repository
